DROP TABLE IF EXISTS T_EMPLOYEE;
DROP TABLE IF EXISTS T_DEPARTMENT;

CREATE TABLE T_DEPARTMENT (
    DEPARTMENT_ID INT PRIMARY KEY IDENTITY(100,1),
    DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE T_EMPLOYEE (
    EMP_ID INT PRIMARY KEY IDENTITY(100,1),
    EMP_NAME VARCHAR(50) NOT NULL,
    EMP_SALARY DECIMAL(18,2) NOT NULL,
	EMP_GENDER VARCHAR(20) NOT NULL,
	EMP_DATE_OF_BIRTH DATETIME NOT NULL,
	EMP_CONTACT_COUNTRY_CODE INT NOT NULL,
	EMP_CONTACT_NO INT NOT NULL,
	EMP_ADDRESS_LINE_1 NVARCHAR(75) NOT NULL,
	EMP_ADDRESS_LINE_2 NVARCHAR(75) NULL,
	EMP_ADDRESS_UNIT_NO VARCHAR(15) NULL,
	EMP_ADDRESS_POSTAL_CODE INT NOT NULL,
	EMP_ADDRESS_COUNTRY VARCHAR(30) NOT NULL,
	EMP_ADDRESS_CITY VARCHAR(30) NULL,
	EMP_ADDRESS_STATE VARCHAR(30) NULL,
    EMP_DEPARTMENT_ID INT NOT NULL,
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT_ID FOREIGN KEY (EMP_DEPARTMENT_ID)
        REFERENCES T_DEPARTMENT(DEPARTMENT_ID) ON DELETE CASCADE
);